# Generated by Django 4.1.6 on 2023-02-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDescriptions',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Titile', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutDetails',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('PhoneNo', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Adddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutHeroImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SliderImage', models.ImageField(upload_to='media/uploads/about/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactHeroImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SliderImages', models.ImageField(upload_to='media/uploads/contact/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=20)),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SliderImages', models.ImageField(upload_to='media/uploads/gallery/')),
                ('GalleryTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderImages',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SliderImages', models.ImageField(upload_to='media/uploads/index/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomHeroImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SliderImage', models.ImageField(upload_to='media/uploads/room/')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=50)),
                ('TypeImage', models.ImageField(upload_to='uploads/')),
                ('TypeDescription', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoomsDetails',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('RoomsNo', models.IntegerField()),
                ('AvailabaleFrom', models.DateField()),
                ('AvailableTo', models.DateField()),
                ('RoomType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.roomtypes')),
            ],
        ),
        migrations.CreateModel(
            name='RoomBookings',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('BookedForm', models.DateField()),
                ('BookedTo', models.DateField()),
                ('NoOfPax', models.IntegerField()),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.customerdetails')),
                ('RoomType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.roomtypes')),
            ],
        ),
    ]
